# Generated by Django 4.0.4 on 2022-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Anaheim', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='CA', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='1313 Disneyland Dr', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(default=92802),
        ),
    ]
